services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: chatty
      POSTGRES_PASSWORD: chatty
      POSTGRES_DB: chatty
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  chatty:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
      - "4001:4001"
    environment:
      - DATABASE_URL=postgres://chatty:chatty@postgres:5432/chatty
    depends_on:
      - postgres

volumes:
  pgdata:
